import { buildTrendStats, summarizeTrend } from "@/lib/travel-trend";
const day=(n:number)=>new Date(Date.now()-n*86400000).toISOString();
const v=(n:number,mode:string,m:number,mins:number,i:number):any=>({id:"v"+i,entry_kind:"resa",travel_mode:mode,distance_m:m,arrived_at:day(n),left_at:new Date(Date.parse(day(n))+mins*60000).toISOString(),lat:59.33,lng:18.06,end_lat:59.34,end_lng:18.02,label:"Jobbet"});
const visits:any[]=[];
let i=0;
for(const n of [2,4,6,9,11,14,16,20,25]) visits.push(v(n,"bil",8000,18,i++));
for(const n of [40,42,45,50,55,60]) visits.push(v(n,"kollektivt",12000,35,i++));
for(const n of [3,8]) visits.push(v(n,"gang_cykel",2000,15,i++));
const places:any=[{id:"w",name:"Jobbet",lat:59.34,lng:18.02,radius_m:200},{id:"h",name:"Hem",lat:59.33,lng:18.06,radius_m:200}];
const stats=buildTrendStats(visits,places);
console.log(JSON.stringify(stats.map(s=>({m:s.mode,d:s.deltaKmPct,dir:s.direction,ok:s.enoughData})),null,1));
console.log("---");
console.log(summarizeTrend(stats,[]));
