/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedArkivRouteImport } from './routes/_authenticated/arkiv'
import { Route as AuthenticatedAttgoraRouteImport } from './routes/_authenticated/attgora'
import { Route as AuthenticatedBarnRouteImport } from './routes/_authenticated/barn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHandlaRouteImport } from './routes/_authenticated/handla'
import { Route as AuthenticatedIptvRouteImport } from './routes/_authenticated/iptv'
import { Route as AuthenticatedJuristRouteImport } from './routes/_authenticated/jurist'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedKalendrarRouteImport } from './routes/_authenticated/kalendrar'
import { Route as AuthenticatedKassaskapRouteImport } from './routes/_authenticated/kassaskap'
import { Route as AuthenticatedPengarRouteImport } from './routes/_authenticated/pengar'
import { Route as AuthenticatedPlatserRouteImport } from './routes/_authenticated/platser'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicOtrcRouteImport } from './routes/api/public/otrc'
import { Route as ApiPublicPlatsRouteImport } from './routes/api/public/plats'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedArkivRoute = AuthenticatedArkivRouteImport.update({
  id: '/arkiv',
  path: '/arkiv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttgoraRoute = AuthenticatedAttgoraRouteImport.update({
  id: '/attgora',
  path: '/attgora',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBarnRoute = AuthenticatedBarnRouteImport.update({
  id: '/barn',
  path: '/barn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHandlaRoute = AuthenticatedHandlaRouteImport.update({
  id: '/handla',
  path: '/handla',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIptvRoute = AuthenticatedIptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJuristRoute = AuthenticatedJuristRouteImport.update({
  id: '/jurist',
  path: '/jurist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalendrarRoute = AuthenticatedKalendrarRouteImport.update({
  id: '/kalendrar',
  path: '/kalendrar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKassaskapRoute = AuthenticatedKassaskapRouteImport.update({
  id: '/kassaskap',
  path: '/kassaskap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengarRoute = AuthenticatedPengarRouteImport.update({
  id: '/pengar',
  path: '/pengar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatserRoute = AuthenticatedPlatserRouteImport.update({
  id: '/platser',
  path: '/platser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOtrcRoute = ApiPublicOtrcRouteImport.update({
  id: '/api/public/otrc',
  path: '/api/public/otrc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlatsRoute = ApiPublicPlatsRouteImport.update({
  id: '/api/public/plats',
  path: '/api/public/plats',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/arkiv': typeof AuthenticatedArkivRoute
  '/attgora': typeof AuthenticatedAttgoraRoute
  '/barn': typeof AuthenticatedBarnRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/handla': typeof AuthenticatedHandlaRoute
  '/iptv': typeof AuthenticatedIptvRoute
  '/jurist': typeof AuthenticatedJuristRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/kalendrar': typeof AuthenticatedKalendrarRoute
  '/kassaskap': typeof AuthenticatedKassaskapRoute
  '/pengar': typeof AuthenticatedPengarRoute
  '/platser': typeof AuthenticatedPlatserRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/otrc': typeof ApiPublicOtrcRoute
  '/api/public/plats': typeof ApiPublicPlatsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/arkiv': typeof AuthenticatedArkivRoute
  '/attgora': typeof AuthenticatedAttgoraRoute
  '/barn': typeof AuthenticatedBarnRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/handla': typeof AuthenticatedHandlaRoute
  '/iptv': typeof AuthenticatedIptvRoute
  '/jurist': typeof AuthenticatedJuristRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/kalendrar': typeof AuthenticatedKalendrarRoute
  '/kassaskap': typeof AuthenticatedKassaskapRoute
  '/pengar': typeof AuthenticatedPengarRoute
  '/platser': typeof AuthenticatedPlatserRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/otrc': typeof ApiPublicOtrcRoute
  '/api/public/plats': typeof ApiPublicPlatsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/arkiv': typeof AuthenticatedArkivRoute
  '/_authenticated/attgora': typeof AuthenticatedAttgoraRoute
  '/_authenticated/barn': typeof AuthenticatedBarnRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/handla': typeof AuthenticatedHandlaRoute
  '/_authenticated/iptv': typeof AuthenticatedIptvRoute
  '/_authenticated/jurist': typeof AuthenticatedJuristRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/kalendrar': typeof AuthenticatedKalendrarRoute
  '/_authenticated/kassaskap': typeof AuthenticatedKassaskapRoute
  '/_authenticated/pengar': typeof AuthenticatedPengarRoute
  '/_authenticated/platser': typeof AuthenticatedPlatserRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/otrc': typeof ApiPublicOtrcRoute
  '/api/public/plats': typeof ApiPublicPlatsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/arkiv'
    | '/attgora'
    | '/barn'
    | '/dashboard'
    | '/handla'
    | '/iptv'
    | '/jurist'
    | '/kalender'
    | '/kalendrar'
    | '/kassaskap'
    | '/pengar'
    | '/platser'
    | '/api/chat'
    | '/api/tts'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/otrc'
    | '/api/public/plats'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/arkiv'
    | '/attgora'
    | '/barn'
    | '/dashboard'
    | '/handla'
    | '/iptv'
    | '/jurist'
    | '/kalender'
    | '/kalendrar'
    | '/kassaskap'
    | '/pengar'
    | '/platser'
    | '/api/chat'
    | '/api/tts'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/otrc'
    | '/api/public/plats'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/arkiv'
    | '/_authenticated/attgora'
    | '/_authenticated/barn'
    | '/_authenticated/dashboard'
    | '/_authenticated/handla'
    | '/_authenticated/iptv'
    | '/_authenticated/jurist'
    | '/_authenticated/kalender'
    | '/_authenticated/kalendrar'
    | '/_authenticated/kassaskap'
    | '/_authenticated/pengar'
    | '/_authenticated/platser'
    | '/api/chat'
    | '/api/tts'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/otrc'
    | '/api/public/plats'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTtsRoute: typeof ApiTtsRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicOtrcRoute: typeof ApiPublicOtrcRoute
  ApiPublicPlatsRoute: typeof ApiPublicPlatsRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/arkiv': {
      id: '/_authenticated/arkiv'
      path: '/arkiv'
      fullPath: '/arkiv'
      preLoaderRoute: typeof AuthenticatedArkivRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attgora': {
      id: '/_authenticated/attgora'
      path: '/attgora'
      fullPath: '/attgora'
      preLoaderRoute: typeof AuthenticatedAttgoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barn': {
      id: '/_authenticated/barn'
      path: '/barn'
      fullPath: '/barn'
      preLoaderRoute: typeof AuthenticatedBarnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/handla': {
      id: '/_authenticated/handla'
      path: '/handla'
      fullPath: '/handla'
      preLoaderRoute: typeof AuthenticatedHandlaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iptv': {
      id: '/_authenticated/iptv'
      path: '/iptv'
      fullPath: '/iptv'
      preLoaderRoute: typeof AuthenticatedIptvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jurist': {
      id: '/_authenticated/jurist'
      path: '/jurist'
      fullPath: '/jurist'
      preLoaderRoute: typeof AuthenticatedJuristRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalendrar': {
      id: '/_authenticated/kalendrar'
      path: '/kalendrar'
      fullPath: '/kalendrar'
      preLoaderRoute: typeof AuthenticatedKalendrarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kassaskap': {
      id: '/_authenticated/kassaskap'
      path: '/kassaskap'
      fullPath: '/kassaskap'
      preLoaderRoute: typeof AuthenticatedKassaskapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengar': {
      id: '/_authenticated/pengar'
      path: '/pengar'
      fullPath: '/pengar'
      preLoaderRoute: typeof AuthenticatedPengarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platser': {
      id: '/_authenticated/platser'
      path: '/platser'
      fullPath: '/platser'
      preLoaderRoute: typeof AuthenticatedPlatserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/otrc': {
      id: '/api/public/otrc'
      path: '/api/public/otrc'
      fullPath: '/api/public/otrc'
      preLoaderRoute: typeof ApiPublicOtrcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plats': {
      id: '/api/public/plats'
      path: '/api/public/plats'
      fullPath: '/api/public/plats'
      preLoaderRoute: typeof ApiPublicPlatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArkivRoute: typeof AuthenticatedArkivRoute
  AuthenticatedAttgoraRoute: typeof AuthenticatedAttgoraRoute
  AuthenticatedBarnRoute: typeof AuthenticatedBarnRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHandlaRoute: typeof AuthenticatedHandlaRoute
  AuthenticatedIptvRoute: typeof AuthenticatedIptvRoute
  AuthenticatedJuristRoute: typeof AuthenticatedJuristRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedKalendrarRoute: typeof AuthenticatedKalendrarRoute
  AuthenticatedKassaskapRoute: typeof AuthenticatedKassaskapRoute
  AuthenticatedPengarRoute: typeof AuthenticatedPengarRoute
  AuthenticatedPlatserRoute: typeof AuthenticatedPlatserRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArkivRoute: AuthenticatedArkivRoute,
  AuthenticatedAttgoraRoute: AuthenticatedAttgoraRoute,
  AuthenticatedBarnRoute: AuthenticatedBarnRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHandlaRoute: AuthenticatedHandlaRoute,
  AuthenticatedIptvRoute: AuthenticatedIptvRoute,
  AuthenticatedJuristRoute: AuthenticatedJuristRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedKalendrarRoute: AuthenticatedKalendrarRoute,
  AuthenticatedKassaskapRoute: AuthenticatedKassaskapRoute,
  AuthenticatedPengarRoute: AuthenticatedPengarRoute,
  AuthenticatedPlatserRoute: AuthenticatedPlatserRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTtsRoute: ApiTtsRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicOtrcRoute: ApiPublicOtrcRoute,
  ApiPublicPlatsRoute: ApiPublicPlatsRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
