/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as VardRouteImport } from './routes/vard'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedArkivRouteImport } from './routes/_authenticated/arkiv'
import { Route as AuthenticatedAttgoraRouteImport } from './routes/_authenticated/attgora'
import { Route as AuthenticatedBarnRouteImport } from './routes/_authenticated/barn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHandlaRouteImport } from './routes/_authenticated/handla'
import { Route as AuthenticatedIptvRouteImport } from './routes/_authenticated/iptv'
import { Route as AuthenticatedJuristRouteImport } from './routes/_authenticated/jurist'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedKalendrarRouteImport } from './routes/_authenticated/kalendrar'
import { Route as AuthenticatedKassaskapRouteImport } from './routes/_authenticated/kassaskap'
import { Route as AuthenticatedPengarRouteImport } from './routes/_authenticated/pengar'
import { Route as AuthenticatedPlatserRouteImport } from './routes/_authenticated/platser'
import { Route as AuthenticatedVRouteImport } from './routes/_authenticated/v'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as VardIndexRouteImport } from './routes/vard.index'
import { Route as VardBrukareRouteImport } from './routes/vard.brukare'
import { Route as VardKommunRouteImport } from './routes/vard.kommun'
import { Route as VardKontaktRouteImport } from './routes/vard.kontakt'
import { Route as VardPersonalRouteImport } from './routes/vard.personal'
import { Route as VardSakerhetRouteImport } from './routes/vard.sakerhet'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedVIndexRouteImport } from './routes/_authenticated/v.index'
import { Route as AuthenticatedVOrganisationerRouteImport } from './routes/_authenticated/v.organisationer'
import { Route as ApiPublicOtrcRouteImport } from './routes/api/public/otrc'
import { Route as ApiPublicPlatsRouteImport } from './routes/api/public/plats'
import { Route as AuthenticatedVKundOrgIdRouteImport } from './routes/_authenticated/v.kund.$orgId'
import { Route as ApiPublicHooksEpostRouteImport } from './routes/api/public/hooks/epost'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const VardRoute = VardRouteImport.update({
  id: '/vard',
  path: '/vard',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedArkivRoute = AuthenticatedArkivRouteImport.update({
  id: '/arkiv',
  path: '/arkiv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttgoraRoute = AuthenticatedAttgoraRouteImport.update({
  id: '/attgora',
  path: '/attgora',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBarnRoute = AuthenticatedBarnRouteImport.update({
  id: '/barn',
  path: '/barn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHandlaRoute = AuthenticatedHandlaRouteImport.update({
  id: '/handla',
  path: '/handla',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIptvRoute = AuthenticatedIptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJuristRoute = AuthenticatedJuristRouteImport.update({
  id: '/jurist',
  path: '/jurist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalendrarRoute = AuthenticatedKalendrarRouteImport.update({
  id: '/kalendrar',
  path: '/kalendrar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKassaskapRoute = AuthenticatedKassaskapRouteImport.update({
  id: '/kassaskap',
  path: '/kassaskap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengarRoute = AuthenticatedPengarRouteImport.update({
  id: '/pengar',
  path: '/pengar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatserRoute = AuthenticatedPlatserRouteImport.update({
  id: '/platser',
  path: '/platser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVRoute = AuthenticatedVRouteImport.update({
  id: '/v',
  path: '/v',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VardIndexRoute = VardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VardRoute,
} as any)
const VardBrukareRoute = VardBrukareRouteImport.update({
  id: '/brukare',
  path: '/brukare',
  getParentRoute: () => VardRoute,
} as any)
const VardKommunRoute = VardKommunRouteImport.update({
  id: '/kommun',
  path: '/kommun',
  getParentRoute: () => VardRoute,
} as any)
const VardKontaktRoute = VardKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => VardRoute,
} as any)
const VardPersonalRoute = VardPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => VardRoute,
} as any)
const VardSakerhetRoute = VardSakerhetRouteImport.update({
  id: '/sakerhet',
  path: '/sakerhet',
  getParentRoute: () => VardRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVIndexRoute = AuthenticatedVIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedVRoute,
} as any)
const AuthenticatedVOrganisationerRoute =
  AuthenticatedVOrganisationerRouteImport.update({
    id: '/organisationer',
    path: '/organisationer',
    getParentRoute: () => AuthenticatedVRoute,
  } as any)
const ApiPublicOtrcRoute = ApiPublicOtrcRouteImport.update({
  id: '/api/public/otrc',
  path: '/api/public/otrc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlatsRoute = ApiPublicPlatsRouteImport.update({
  id: '/api/public/plats',
  path: '/api/public/plats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVKundOrgIdRoute = AuthenticatedVKundOrgIdRouteImport.update({
  id: '/kund/$orgId',
  path: '/kund/$orgId',
  getParentRoute: () => AuthenticatedVRoute,
} as any)
const ApiPublicHooksEpostRoute = ApiPublicHooksEpostRouteImport.update({
  id: '/api/public/hooks/epost',
  path: '/api/public/hooks/epost',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/vard': typeof VardRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/arkiv': typeof AuthenticatedArkivRoute
  '/attgora': typeof AuthenticatedAttgoraRoute
  '/barn': typeof AuthenticatedBarnRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/handla': typeof AuthenticatedHandlaRoute
  '/iptv': typeof AuthenticatedIptvRoute
  '/jurist': typeof AuthenticatedJuristRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/kalendrar': typeof AuthenticatedKalendrarRoute
  '/kassaskap': typeof AuthenticatedKassaskapRoute
  '/pengar': typeof AuthenticatedPengarRoute
  '/platser': typeof AuthenticatedPlatserRoute
  '/v': typeof AuthenticatedVRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/vard/brukare': typeof VardBrukareRoute
  '/vard/kommun': typeof VardKommunRoute
  '/vard/kontakt': typeof VardKontaktRoute
  '/vard/personal': typeof VardPersonalRoute
  '/vard/sakerhet': typeof VardSakerhetRoute
  '/vard/': typeof VardIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/v/organisationer': typeof AuthenticatedVOrganisationerRoute
  '/api/public/otrc': typeof ApiPublicOtrcRoute
  '/api/public/plats': typeof ApiPublicPlatsRoute
  '/v/': typeof AuthenticatedVIndexRoute
  '/v/kund/$orgId': typeof AuthenticatedVKundOrgIdRoute
  '/api/public/hooks/epost': typeof ApiPublicHooksEpostRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/arkiv': typeof AuthenticatedArkivRoute
  '/attgora': typeof AuthenticatedAttgoraRoute
  '/barn': typeof AuthenticatedBarnRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/handla': typeof AuthenticatedHandlaRoute
  '/iptv': typeof AuthenticatedIptvRoute
  '/jurist': typeof AuthenticatedJuristRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/kalendrar': typeof AuthenticatedKalendrarRoute
  '/kassaskap': typeof AuthenticatedKassaskapRoute
  '/pengar': typeof AuthenticatedPengarRoute
  '/platser': typeof AuthenticatedPlatserRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/vard/brukare': typeof VardBrukareRoute
  '/vard/kommun': typeof VardKommunRoute
  '/vard/kontakt': typeof VardKontaktRoute
  '/vard/personal': typeof VardPersonalRoute
  '/vard/sakerhet': typeof VardSakerhetRoute
  '/vard': typeof VardIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/v/organisationer': typeof AuthenticatedVOrganisationerRoute
  '/api/public/otrc': typeof ApiPublicOtrcRoute
  '/api/public/plats': typeof ApiPublicPlatsRoute
  '/v': typeof AuthenticatedVIndexRoute
  '/v/kund/$orgId': typeof AuthenticatedVKundOrgIdRoute
  '/api/public/hooks/epost': typeof ApiPublicHooksEpostRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/vard': typeof VardRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/arkiv': typeof AuthenticatedArkivRoute
  '/_authenticated/attgora': typeof AuthenticatedAttgoraRoute
  '/_authenticated/barn': typeof AuthenticatedBarnRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/handla': typeof AuthenticatedHandlaRoute
  '/_authenticated/iptv': typeof AuthenticatedIptvRoute
  '/_authenticated/jurist': typeof AuthenticatedJuristRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/kalendrar': typeof AuthenticatedKalendrarRoute
  '/_authenticated/kassaskap': typeof AuthenticatedKassaskapRoute
  '/_authenticated/pengar': typeof AuthenticatedPengarRoute
  '/_authenticated/platser': typeof AuthenticatedPlatserRoute
  '/_authenticated/v': typeof AuthenticatedVRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/vard/brukare': typeof VardBrukareRoute
  '/vard/kommun': typeof VardKommunRoute
  '/vard/kontakt': typeof VardKontaktRoute
  '/vard/personal': typeof VardPersonalRoute
  '/vard/sakerhet': typeof VardSakerhetRoute
  '/vard/': typeof VardIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/v/organisationer': typeof AuthenticatedVOrganisationerRoute
  '/api/public/otrc': typeof ApiPublicOtrcRoute
  '/api/public/plats': typeof ApiPublicPlatsRoute
  '/_authenticated/v/': typeof AuthenticatedVIndexRoute
  '/_authenticated/v/kund/$orgId': typeof AuthenticatedVKundOrgIdRoute
  '/api/public/hooks/epost': typeof ApiPublicHooksEpostRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/vard'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/arkiv'
    | '/attgora'
    | '/barn'
    | '/dashboard'
    | '/handla'
    | '/iptv'
    | '/jurist'
    | '/kalender'
    | '/kalendrar'
    | '/kassaskap'
    | '/pengar'
    | '/platser'
    | '/v'
    | '/api/chat'
    | '/api/tts'
    | '/invite/$token'
    | '/vard/brukare'
    | '/vard/kommun'
    | '/vard/kontakt'
    | '/vard/personal'
    | '/vard/sakerhet'
    | '/vard/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/v/organisationer'
    | '/api/public/otrc'
    | '/api/public/plats'
    | '/v/'
    | '/v/kund/$orgId'
    | '/api/public/hooks/epost'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/arkiv'
    | '/attgora'
    | '/barn'
    | '/dashboard'
    | '/handla'
    | '/iptv'
    | '/jurist'
    | '/kalender'
    | '/kalendrar'
    | '/kassaskap'
    | '/pengar'
    | '/platser'
    | '/api/chat'
    | '/api/tts'
    | '/invite/$token'
    | '/vard/brukare'
    | '/vard/kommun'
    | '/vard/kontakt'
    | '/vard/personal'
    | '/vard/sakerhet'
    | '/vard'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/v/organisationer'
    | '/api/public/otrc'
    | '/api/public/plats'
    | '/v'
    | '/v/kund/$orgId'
    | '/api/public/hooks/epost'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/vard'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/arkiv'
    | '/_authenticated/attgora'
    | '/_authenticated/barn'
    | '/_authenticated/dashboard'
    | '/_authenticated/handla'
    | '/_authenticated/iptv'
    | '/_authenticated/jurist'
    | '/_authenticated/kalender'
    | '/_authenticated/kalendrar'
    | '/_authenticated/kassaskap'
    | '/_authenticated/pengar'
    | '/_authenticated/platser'
    | '/_authenticated/v'
    | '/api/chat'
    | '/api/tts'
    | '/invite/$token'
    | '/vard/brukare'
    | '/vard/kommun'
    | '/vard/kontakt'
    | '/vard/personal'
    | '/vard/sakerhet'
    | '/vard/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/v/organisationer'
    | '/api/public/otrc'
    | '/api/public/plats'
    | '/_authenticated/v/'
    | '/_authenticated/v/kund/$orgId'
    | '/api/public/hooks/epost'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  VardRoute: typeof VardRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTtsRoute: typeof ApiTtsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicOtrcRoute: typeof ApiPublicOtrcRoute
  ApiPublicPlatsRoute: typeof ApiPublicPlatsRoute
  ApiPublicHooksEpostRoute: typeof ApiPublicHooksEpostRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vard': {
      id: '/vard'
      path: '/vard'
      fullPath: '/vard'
      preLoaderRoute: typeof VardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/arkiv': {
      id: '/_authenticated/arkiv'
      path: '/arkiv'
      fullPath: '/arkiv'
      preLoaderRoute: typeof AuthenticatedArkivRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attgora': {
      id: '/_authenticated/attgora'
      path: '/attgora'
      fullPath: '/attgora'
      preLoaderRoute: typeof AuthenticatedAttgoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barn': {
      id: '/_authenticated/barn'
      path: '/barn'
      fullPath: '/barn'
      preLoaderRoute: typeof AuthenticatedBarnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/handla': {
      id: '/_authenticated/handla'
      path: '/handla'
      fullPath: '/handla'
      preLoaderRoute: typeof AuthenticatedHandlaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iptv': {
      id: '/_authenticated/iptv'
      path: '/iptv'
      fullPath: '/iptv'
      preLoaderRoute: typeof AuthenticatedIptvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jurist': {
      id: '/_authenticated/jurist'
      path: '/jurist'
      fullPath: '/jurist'
      preLoaderRoute: typeof AuthenticatedJuristRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalendrar': {
      id: '/_authenticated/kalendrar'
      path: '/kalendrar'
      fullPath: '/kalendrar'
      preLoaderRoute: typeof AuthenticatedKalendrarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kassaskap': {
      id: '/_authenticated/kassaskap'
      path: '/kassaskap'
      fullPath: '/kassaskap'
      preLoaderRoute: typeof AuthenticatedKassaskapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengar': {
      id: '/_authenticated/pengar'
      path: '/pengar'
      fullPath: '/pengar'
      preLoaderRoute: typeof AuthenticatedPengarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platser': {
      id: '/_authenticated/platser'
      path: '/platser'
      fullPath: '/platser'
      preLoaderRoute: typeof AuthenticatedPlatserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/v': {
      id: '/_authenticated/v'
      path: '/v'
      fullPath: '/v'
      preLoaderRoute: typeof AuthenticatedVRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vard/': {
      id: '/vard/'
      path: '/'
      fullPath: '/vard/'
      preLoaderRoute: typeof VardIndexRouteImport
      parentRoute: typeof VardRoute
    }
    '/vard/brukare': {
      id: '/vard/brukare'
      path: '/brukare'
      fullPath: '/vard/brukare'
      preLoaderRoute: typeof VardBrukareRouteImport
      parentRoute: typeof VardRoute
    }
    '/vard/kommun': {
      id: '/vard/kommun'
      path: '/kommun'
      fullPath: '/vard/kommun'
      preLoaderRoute: typeof VardKommunRouteImport
      parentRoute: typeof VardRoute
    }
    '/vard/kontakt': {
      id: '/vard/kontakt'
      path: '/kontakt'
      fullPath: '/vard/kontakt'
      preLoaderRoute: typeof VardKontaktRouteImport
      parentRoute: typeof VardRoute
    }
    '/vard/personal': {
      id: '/vard/personal'
      path: '/personal'
      fullPath: '/vard/personal'
      preLoaderRoute: typeof VardPersonalRouteImport
      parentRoute: typeof VardRoute
    }
    '/vard/sakerhet': {
      id: '/vard/sakerhet'
      path: '/sakerhet'
      fullPath: '/vard/sakerhet'
      preLoaderRoute: typeof VardSakerhetRouteImport
      parentRoute: typeof VardRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/v/': {
      id: '/_authenticated/v/'
      path: '/'
      fullPath: '/v/'
      preLoaderRoute: typeof AuthenticatedVIndexRouteImport
      parentRoute: typeof AuthenticatedVRoute
    }
    '/_authenticated/v/organisationer': {
      id: '/_authenticated/v/organisationer'
      path: '/organisationer'
      fullPath: '/v/organisationer'
      preLoaderRoute: typeof AuthenticatedVOrganisationerRouteImport
      parentRoute: typeof AuthenticatedVRoute
    }
    '/api/public/otrc': {
      id: '/api/public/otrc'
      path: '/api/public/otrc'
      fullPath: '/api/public/otrc'
      preLoaderRoute: typeof ApiPublicOtrcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plats': {
      id: '/api/public/plats'
      path: '/api/public/plats'
      fullPath: '/api/public/plats'
      preLoaderRoute: typeof ApiPublicPlatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/v/kund/$orgId': {
      id: '/_authenticated/v/kund/$orgId'
      path: '/kund/$orgId'
      fullPath: '/v/kund/$orgId'
      preLoaderRoute: typeof AuthenticatedVKundOrgIdRouteImport
      parentRoute: typeof AuthenticatedVRoute
    }
    '/api/public/hooks/epost': {
      id: '/api/public/hooks/epost'
      path: '/api/public/hooks/epost'
      fullPath: '/api/public/hooks/epost'
      preLoaderRoute: typeof ApiPublicHooksEpostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedVRouteChildren {
  AuthenticatedVOrganisationerRoute: typeof AuthenticatedVOrganisationerRoute
  AuthenticatedVIndexRoute: typeof AuthenticatedVIndexRoute
  AuthenticatedVKundOrgIdRoute: typeof AuthenticatedVKundOrgIdRoute
}

const AuthenticatedVRouteChildren: AuthenticatedVRouteChildren = {
  AuthenticatedVOrganisationerRoute: AuthenticatedVOrganisationerRoute,
  AuthenticatedVIndexRoute: AuthenticatedVIndexRoute,
  AuthenticatedVKundOrgIdRoute: AuthenticatedVKundOrgIdRoute,
}

const AuthenticatedVRouteWithChildren = AuthenticatedVRoute._addFileChildren(
  AuthenticatedVRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArkivRoute: typeof AuthenticatedArkivRoute
  AuthenticatedAttgoraRoute: typeof AuthenticatedAttgoraRoute
  AuthenticatedBarnRoute: typeof AuthenticatedBarnRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHandlaRoute: typeof AuthenticatedHandlaRoute
  AuthenticatedIptvRoute: typeof AuthenticatedIptvRoute
  AuthenticatedJuristRoute: typeof AuthenticatedJuristRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedKalendrarRoute: typeof AuthenticatedKalendrarRoute
  AuthenticatedKassaskapRoute: typeof AuthenticatedKassaskapRoute
  AuthenticatedPengarRoute: typeof AuthenticatedPengarRoute
  AuthenticatedPlatserRoute: typeof AuthenticatedPlatserRoute
  AuthenticatedVRoute: typeof AuthenticatedVRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArkivRoute: AuthenticatedArkivRoute,
  AuthenticatedAttgoraRoute: AuthenticatedAttgoraRoute,
  AuthenticatedBarnRoute: AuthenticatedBarnRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHandlaRoute: AuthenticatedHandlaRoute,
  AuthenticatedIptvRoute: AuthenticatedIptvRoute,
  AuthenticatedJuristRoute: AuthenticatedJuristRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedKalendrarRoute: AuthenticatedKalendrarRoute,
  AuthenticatedKassaskapRoute: AuthenticatedKassaskapRoute,
  AuthenticatedPengarRoute: AuthenticatedPengarRoute,
  AuthenticatedPlatserRoute: AuthenticatedPlatserRoute,
  AuthenticatedVRoute: AuthenticatedVRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface VardRouteChildren {
  VardBrukareRoute: typeof VardBrukareRoute
  VardKommunRoute: typeof VardKommunRoute
  VardKontaktRoute: typeof VardKontaktRoute
  VardPersonalRoute: typeof VardPersonalRoute
  VardSakerhetRoute: typeof VardSakerhetRoute
  VardIndexRoute: typeof VardIndexRoute
}

const VardRouteChildren: VardRouteChildren = {
  VardBrukareRoute: VardBrukareRoute,
  VardKommunRoute: VardKommunRoute,
  VardKontaktRoute: VardKontaktRoute,
  VardPersonalRoute: VardPersonalRoute,
  VardSakerhetRoute: VardSakerhetRoute,
  VardIndexRoute: VardIndexRoute,
}

const VardRouteWithChildren = VardRoute._addFileChildren(VardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  VardRoute: VardRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTtsRoute: ApiTtsRoute,
  InviteTokenRoute: InviteTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicOtrcRoute: ApiPublicOtrcRoute,
  ApiPublicPlatsRoute: ApiPublicPlatsRoute,
  ApiPublicHooksEpostRoute: ApiPublicHooksEpostRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
